### ISSUE TITLE
v6 compatibility

### ISSUE THREAD

**Issue by gdugas** [95ulisse/js-notifyicon#1]
Hi,

This is the only lightweight tray solution for windows 7 i found. But unfortunately, it's incompatible with node v6.*.
Can we expect to see this project working for the newest versions of node ?

Cheers,
G.

**Comment by iAm-Qin** [comment]
> Hi,
> 
> This is the only lightweight tray solution for windows 7 i found. But unfortunately, it's incompatible with node v6.*.
> Can we expect to see this project working for the newest versions of node ?
> 
> Cheers,
> G.


Hello, @gdugas 

Did you build successfully? What version of node and node-gyp did you use?
I'm using node 5.12.0 and node-gyp 3.8.0. Build failed.

Yours,
Q

**Comment by gdugas** [comment]
Sorry @jianweiqin, but i don't, and this project seem to be inactive.

**Comment by 95ulisse** [comment]
Hi @gdugas @jianweiqin.
Sorry, but yes this project is very old, and no longer maintained.

**Comment by iAm-Qin** [comment]
@gdugas Successfully on node 0.10.48 and node-gyp 3.8.0
@95ulisse Would you please write the version of all the tools you use to build your project next time? It cost me much time!
